version: "3.5"
services:
  db:
    image: ${dockerId}/learningsql:${version}
    container_name: learningsql-db
    build:
      context: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: bank
    networks:
      sql-network:
        ipv4_address: 10.0.0.2

  admin:
    image: phpmyadmin/phpmyadmin
    container_name: learningsql-admin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    networks:
      sql-network:
        ipv4_address: 10.0.0.3

  configdummy:
    build: .
    container_name: learningsql-configdummy
    depends_on: 
      - db
    restart: on-failure
    networks:
      sql-network:
        ipv4_address: 10.0.0.10
networks:
  sql-network:
    name: learningsql-network
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/20
